version: "3"
services:
  postgres_db:
    image: postgres
    container_name: postgres
    restart: on-failure:3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: google_api
  google_api:
    build: .
    container_name: google-api
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prom
      GOOGLE-API_AUTHCODE:
      GOOGLE-API_REFRESHTOKEN:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/google_api
      TZ: Europe/Moscow
    ports:
      - "8100:8100"
    links:
      - postgres_db