version: "3"
services:
  postgres_db:
    image: postgres
    container_name: postgres
    restart: on-failure:3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: google_api
  google_api:
    build: .
    container_name: google-api
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prom
      GOOGLE-API_CLIENTID: 460334817822-6ahvhi4snl7l0actahhbg9tik5cr50jv.apps.googleusercontent.com
      GOOGLE-API_CLIENTSECRET: amPG4CcLO5j-mu1dNMHZaZkw
      GOOGLE-API_REFRESHTOKEN: 1//0cEJPDB_nffFZCgYIARAAGAwSNwF-L9Irrw-SwPscXDfg8A8Auivy8RKvzkJsALszutRaU42LBjPUT30sNIW1-9_R2guPb4oConI
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/google_api
      TZ: Europe/Moscow
    ports:
      - "8100:8100"
    links:
      - postgres_db