server:
  port: 8100
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    parser:
      allow-backslash-escaping-any-character: true
  profiles:
    active: dev

google-api:
  clientId: 460334817822-6ahvhi4snl7l0actahhbg9tik5cr50jv.apps.googleusercontent.com
  clientSecret: amPG4CcLO5j-mu1dNMHZaZkw